<script>
import Button from "@/components/Button.vue";
import { ErrorMessage, Field, Form } from "vee-validate";
import * as yup from "yup";
import axios from "axios";
import router from "@/router/index.js";
import { useAuthStore } from "@/storage/authStorage";

const urlBackend = import.meta.env.VITE_BACKEND_URL;

export default {
  /**
   * @vue-component
   * @name Authenticator2faVerification
   * @description This component handles the verification process for two-factor authentication using an authenticator app. It fetches and displays a QR code for the user to scan with their authenticator app, and then prompts the user to enter the verification code generated by the app. Upon successful verification, it logs the user in and redirects them to the vault.
   */
  name: "Authenticator2faVerification",
  components: { ErrorMessage, Field, Form, Button },
  data() {
    return {
      qrCodeDataUri: '',
      loadingQrCode: true,
      qrCodeError: null,
      schema: yup.object().shape({
        code: yup.string()
          .required("Código requerido")
          .matches(/^[0-9]{6}$/, "El código debe ser de 6 dígitos numéricos"),
      }),
      authStore: useAuthStore() // Move authStore to data for Options API
    };
  },
  methods: {
    async onSubmit(values, actions) {
      if (!actions.errors) {
        try {
          const response = await axios.post(`${urlBackend}/auth/2fa/verify`, values, {headers: {
              Authorization: `Bearer ${localStorage.getItem("token")}`,
            }})
          if (response.status === 200) {
            this.authStore.login(response.data.user);
            await router.push("/vault");
          }

          console.log("Verification successful", response);

        } catch (error) {

          console.error("Verification failed", error);
          if (error.response && error.response.data && error.response.data.message) {
            alert(error.response.data.message);
          } else {
            alert("Error verifying code. Please try again.");
          }
        }
      }
    },
    async setUpQr() {
      this.loadingQrCode = true;
      this.qrCodeError = null;
      try {
        const response = await axios.post(`${urlBackend}/auth/2fa/setup`, { 'two_factor_type': 'app' }, {headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          }});
        this.qrCodeDataUri = `data:image/png;base64,${response.data.qr_code_url}`;
      } catch (error) {

        this.qrCodeError = "Failed to generate QR code. Please try again later.";
      } finally {
        this.loadingQrCode = false;
      }
    },
  },
  mounted() {
    this.setUpQr();
  },
};
</script>

Copy

<template>
  <div class="two-fa">
    <section class="two-fa__section">
      <h1 class="two-fa__title">Configura tu Authenticator App</h1>
      <p class="two-fa__instructions">Escanea el código QR con tu aplicación de autenticación (Google Authenticator, Authy, etc.) para generar códigos de verificación.</p>
    </section>

    <section v-if="loadingQrCode" class="two-fa__loading two-fa__loading--visible">
      <p>Cargando código QR...</p>
    </section>

    <section v-else-if="qrCodeError" class="two-fa__error two-fa__error--active">
      <p class="two-fa__error-text">{{ qrCodeError }}</p>
      <Button
          text="Reintentar Cargar QR"
          @click="setUpQr"
          class="two-fa__retry-button"
      />
    </section>

    <section v-else-if="qrCodeDataUri" class="two-fa__section">
      <div class="two-fa__qr-container">
        <img
            :src="qrCodeDataUri"
            alt="Código QR para Authenticator App"
            class="two-fa__qr-image"
        />
      </div>

      <p class="two-fa__instructions">Escanea este código QR con tu Authenticator App.</p>

      <Form
          @submit="onSubmit"
          :validation-schema="schema"
          class="two-fa__form"
      >
        <div class="two-fa__form-group">
          <label for="code" class="two-fa__label">Código de Verificación</label>
          <Field
              type="text"
              id="code"
              name="code"
              placeholder="Introduce el código de 6 dígitos"
              class="two-fa__input"
          />
          <ErrorMessage name="code" class="two-fa__error-text" />
        </div>
        <Button
            type="submit"
            text="Verificar Código"
            class="two-fa__submit-button"
        />
      </Form>
    </section>
  </div>
</template>

<style scoped lang="sass">
@use "@/sass/pages/authAppVerificator"
</style>